name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Unit Tests cekvalid
      run: bash ./gradlew app:testDebug --tests=com.skripsi.andra.cekvalidTest
      
    - name: Run Unit Tests lupapassTest
      run: bash ./gradlew app:testDebug --tests=com.skripsi.andra.lupapassTest
      
    - name: Run Unit Tests SigninTest
      run: bash ./gradlew app:testDebug --tests=com.skripsi.andra.SigninTest
      
    - name: Run Unit Tests signupTest
      run: bash ./gradlew app:testDebug --tests=com.skripsi.andra.signupTest
      
    - name: Build apk
      run: ./gradlew assembleDebug

    - name: upload ke Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
      with:
        appId: '1:521644696500:android:a021b3132a70c4636e48e1'
        token: '1//0geuNhTLIxJbiCgYIARAAGBASNwF-L9IrPdw-OYX222swE85aBVPpAMctAlXZlAJm0k-1YwrUtZF8Etpzh3dedfVN1UlHWSqRzaA'
        groups: testapp
        file: app/build/outputs/apk/debug/app-debug.apk
